apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  labels:
    app: order-processor
data:
  SERVICEBUS_TOPIC_CONNECTIONSTRING: "RW5kcG9pbnQ9c2I6Ly9lcnlkcm5zZXJ2aWNlYnVzLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9a2VkYTtTaGFyZWRBY2Nlc3NLZXk9Wjh5SW5tVlp4WXpXbGZPVERkTDVzcWhXRFgrOSt1TVJyZSs0cFJLMVladz07RW50aXR5UGF0aD1xdWV1ZW9uZQ=="